export const PROGRAMMATIC_TASK_TYPES = [
  { id: "campaign_setup", label: "Campaign Setup" },
  { id: "creative_addition", label: "Creative Addition" },
  { id: "creative_swap", label: "Creative Swap" },
  { id: "campaign_renewal", label: "Campaign Renewal" },
  { id: "url_validation_utm_update", label: "URL Validation / UTM Update" },
] as const;

export type ProgrammaticTaskTypeId = (typeof PROGRAMMATIC_TASK_TYPES)[number]["id"];

export const PROGRAMMATIC_OBJECTIVES = [
  { id: "awareness", label: "Awareness" },
  { id: "consideration", label: "Consideration" },
  { id: "conversion", label: "Conversion" },
  { id: "custom", label: "Custom objective" },
] as const;

export type ProgrammaticObjectiveId = (typeof PROGRAMMATIC_OBJECTIVES)[number]["id"];

export const PROGRAMMATIC_OBJECTIVE_CUSTOM: ProgrammaticObjectiveId = "custom";

export const MIN_PROGRAMMATIC_AD_GROUPS = 1;
export const MAX_PROGRAMMATIC_AD_GROUPS = 10;
export const PROGRAMMATIC_AD_GROUP_COUNT_OPTIONS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const;

/** @deprecated Legacy preset shape — kept for normalizing stored campaigns. */
export type ProgrammaticAdGroupPreset = {
  key: string;
  label: string;
  customName?: boolean;
};

export type ProgrammaticAdGroup = {
  id: string;
  name: string;
  objective: string;
  customObjective?: string;
};

type LegacyProgrammaticAdGroup = ProgrammaticAdGroup & {
  key?: string;
  label?: string;
  customName?: string;
  customNameRequired?: boolean;
};

function createAdGroupId(index: number): string {
  return `ad-group-${index + 1}-${Date.now().toString(36)}`;
}

/** Auto-generated placeholder names — never pre-fill these in the UI. */
export function stripAutoGeneratedAdGroupName(name: string | undefined | null): string {
  const trimmed = String(name || "").trim();
  if (!trimmed) return "";
  return /^Ad Group \d+$/i.test(trimmed) ? "" : trimmed;
}

type NormalizeProgrammaticAdGroupOptions = {
  /** When true, only keep explicit user-entered names (Campaign Setup). */
  forSetup?: boolean;
};

/** Normalize ad groups saved with the old preset label/customName format. */
export function normalizeProgrammaticAdGroup(
  group: LegacyProgrammaticAdGroup,
  index = 0,
  options: NormalizeProgrammaticAdGroupOptions = {},
): ProgrammaticAdGroup {
  const forSetup = options.forSetup ?? false;
  const explicitName = stripAutoGeneratedAdGroupName(group?.name);

  let name = explicitName;
  if (!name && !forSetup) {
    const legacyName = group.customName?.trim() || group.label?.trim() || "";
    name = stripAutoGeneratedAdGroupName(legacyName);
  }

  return {
    id: group.id || createAdGroupId(index),
    name,
    objective: group.objective || "",
    customObjective: group.customObjective?.trim() || undefined,
  };
}

export function normalizeProgrammaticAdGroups(
  groups: LegacyProgrammaticAdGroup[] = [],
  options: NormalizeProgrammaticAdGroupOptions = {},
): ProgrammaticAdGroup[] {
  return groups.map((group, index) => normalizeProgrammaticAdGroup(group, index, options));
}

export function createProgrammaticAdGroup(index: number, existing?: Partial<ProgrammaticAdGroup>): ProgrammaticAdGroup {
  return {
    id: existing?.id || createAdGroupId(index),
    name: stripAutoGeneratedAdGroupName(existing?.name),
    objective: existing?.objective || "",
    customObjective: existing?.customObjective?.trim() || undefined,
  };
}

export function buildProgrammaticAdGroups(count: number, previous: LegacyProgrammaticAdGroup[] = []): ProgrammaticAdGroup[] {
  const safeCount = Math.max(MIN_PROGRAMMATIC_AD_GROUPS, Math.min(MAX_PROGRAMMATIC_AD_GROUPS, count));
  const result: ProgrammaticAdGroup[] = [];

  for (let index = 0; index < safeCount; index += 1) {
    const prev = previous[index];
    result.push(createProgrammaticAdGroup(index, prev ? {
      id: prev.id,
      name: prev.name,
      objective: prev.objective,
      customObjective: prev.customObjective,
    } : undefined));
  }

  return result;
}

export function addProgrammaticAdGroup(groups: ProgrammaticAdGroup[]): ProgrammaticAdGroup[] {
  if (groups.length >= MAX_PROGRAMMATIC_AD_GROUPS) return groups;
  return [...groups, createProgrammaticAdGroup(groups.length)];
}

export function removeProgrammaticAdGroup(groups: ProgrammaticAdGroup[], groupId: string): ProgrammaticAdGroup[] {
  if (groups.length <= MIN_PROGRAMMATIC_AD_GROUPS) return groups;
  return groups.filter((group) => group.id !== groupId);
}

export function getProgrammaticAdGroupDisplayName(group: Pick<ProgrammaticAdGroup, "name"> | LegacyProgrammaticAdGroup): string {
  if ("name" in group && group.name?.trim()) {
    return group.name.trim();
  }
  const legacy = group as LegacyProgrammaticAdGroup;
  if (legacy.customName?.trim()) return legacy.customName.trim();
  if (legacy.label?.trim()) return legacy.label.trim();
  return "Unnamed Ad Group";
}

export function isProgrammaticCampaignSetup(taskType: string | null | undefined): boolean {
  return taskType === "campaign_setup";
}

export function isProgrammaticCreativeAddition(taskType: string | null | undefined): boolean {
  return taskType === "creative_addition";
}

export function isProgrammaticCreativeReplacement(taskType: string | null | undefined): boolean {
  return taskType === "creative_swap" || taskType === "creative_replacement";
}

/** @alias isProgrammaticCreativeReplacement */
export const isProgrammaticCreativeSwap = isProgrammaticCreativeReplacement;

export function isProgrammaticCampaignRenewal(taskType: string | null | undefined): boolean {
  return taskType === "campaign_renewal";
}

export function isProgrammaticUrlValidationUtmUpdate(taskType: string | null | undefined): boolean {
  return taskType === "url_validation_utm_update" || taskType === "url_validation" || taskType === "utm_change";
}

const TASK_TYPE_LABELS: Record<string, string> = {
  campaign_setup: "Campaign Setup",
  creative_addition: "Creative Addition",
  creative_swap: "Creative Swap",
  creative_replacement: "Creative Swap",
  campaign_renewal: "Campaign Renewal",
  url_validation_utm_update: "URL/UTM Validation",
  url_validation: "URL/UTM Validation",
  utm_change: "URL/UTM Validation",
};

/** Human-readable label for dashboard and download history. */
export function labelProgrammaticTaskType(taskType: string | null | undefined): string {
  if (!taskType?.trim()) return "—";
  const normalized = taskType.trim();
  if (TASK_TYPE_LABELS[normalized]) return TASK_TYPE_LABELS[normalized];
  const fromList = PROGRAMMATIC_TASK_TYPES.find((item) => item.id === normalized);
  if (fromList) return fromList.label;
  return normalized.replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

/** Update flows that must reuse an existing campaign ID — never mint a new one. */
export function isProgrammaticCampaignUpdateTask(taskType: string | null | undefined): boolean {
  return isProgrammaticCreativeAddition(taskType)
    || isProgrammaticCreativeReplacement(taskType)
    || isProgrammaticCampaignRenewal(taskType)
    || isProgrammaticUrlValidationUtmUpdate(taskType);
}

export function isProgrammaticAdGroupConfigComplete(groups: ProgrammaticAdGroup[]): boolean {
  if (!groups.length) return false;
  return groups.every((group) => {
    if (!group.name?.trim()) return false;
    if (!group.objective) return false;
    if (group.objective === PROGRAMMATIC_OBJECTIVE_CUSTOM) {
      return Boolean(group.customObjective?.trim());
    }
    return true;
  });
}

export function getProgrammaticAdGroupObjectiveLabel(group: ProgrammaticAdGroup): string {
  if (group.objective === PROGRAMMATIC_OBJECTIVE_CUSTOM) {
    return group.customObjective?.trim() || "Custom objective";
  }
  const match = PROGRAMMATIC_OBJECTIVES.find((item) => item.id === group.objective);
  return match?.label || group.objective || "Not set";
}

export function isProgrammaticAdGroupSelectionComplete(
  groups: ProgrammaticAdGroup[],
  selectedGroupIds: string[],
  applyToAll: boolean,
): boolean {
  if (!groups.length) return true;
  if (applyToAll) return true;
  return selectedGroupIds.some((id) => groups.some((group) => group.id === id));
}

export function getPrimaryProgrammaticObjective(groups: ProgrammaticAdGroup[]): string {
  const withObjective = groups.find((group) => group.objective && group.objective !== PROGRAMMATIC_OBJECTIVE_CUSTOM);
  return withObjective?.objective || groups.find((group) => group.objective)?.objective || "";
}

export function getProgrammaticCampaignGoalFromAdGroups(groups: ProgrammaticAdGroup[]): string {
  const standard = groups.find((group) => group.objective && group.objective !== PROGRAMMATIC_OBJECTIVE_CUSTOM);
  if (standard?.objective) return standard.objective;
  const custom = groups.find((group) => group.objective === PROGRAMMATIC_OBJECTIVE_CUSTOM && group.customObjective?.trim());
  if (custom?.customObjective) return custom.customObjective.trim();
  return "";
}

export function filterProgrammaticAdGroupsBySelection(
  groups: ProgrammaticAdGroup[],
  selectedGroupIds: string[],
  applyToAll: boolean,
): ProgrammaticAdGroup[] {
  if (!groups.length) return [];
  if (applyToAll) return groups;
  if (!selectedGroupIds.length) return [];
  const selected = new Set(selectedGroupIds);
  return groups.filter((group) => selected.has(group.id));
}

export function filterImageFiles(files: FileList | File[] | null | undefined): File[] {
  return Array.from(files || []).filter((file) => {
    const type = String(file.type || "").toLowerCase();
    if (type.startsWith("image/")) return true;
    return /\.(png|jpe?g|gif|webp|bmp|svg|avif|tiff?|ico)$/i.test(file.name);
  });
}
